apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-release-specialist-risk-demo
  labels:
    app: ai-release-specialist-risk-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-release-specialist-risk-demo
  template:
    metadata:
      labels:
        app: ai-release-specialist-risk-demo
    spec:
      containers:
        - name: ai-release-specialist-risk-demo
          image: koderover.tencentcloudcr.com/koderover-demo/service1:latest
          imagePullPolicy: Always
          command:
            - /workspace/service1
          ports:
            - name: http
              containerPort: 20221
---
apiVersion: v1
kind: Service
metadata:
  name: ai-release-specialist-risk-demo
  labels:
    app: ai-release-specialist-risk-demo
spec:
  type: ClusterIP
  selector:
    app: ai-release-specialist-risk-demo
  ports:
    - name: http
      port: 8080
      targetPort: 20221
